### ISSUE TITLE
Bundle dependencies when building for Linux

### ISSUE THREAD

**Issue by artrz** [igorski/fogpad#4]
Hello @igorski.

A couple of months ago I built this and the other VSTs and after uninstalling the sdk all the plugins broke. Is there a way to bundle the dependencies when building so it's not necessary to keep the sdk installed?
Thanks!

**Comment by igorski** [comment]
Hi @artrz excuse the delay in my reply.

If I understand correctly the built plugins no longer work when you uninstall the SDK ? That should indeed not be the case. The dependencies should be bundled into the binary during compilation phase. Does this issue still occur for the latest version of the code base ?

**Comment by artrz** [comment]
Unfortunately, I don't currently have a Linux box to test it. I'll gladly try again when I'm able to and report it back.
Happy holidays!
