### ISSUE TITLE
Stable release tag

### ISSUE THREAD

**Issue by cbix** [igorski/fogpad#5]
In order to get packaged for Arch Linux, the repo should use git tags for release versions. Having release versions for audio plugins is in general a good idea as it simplifies sharing DAW sessions across machines :)

**Comment by igorski** [comment]
Hi @cbix excuse the delay in my reply, all plugins now actually use release tags (also referencing which Steinberg SDK version was used to build them against). This includes the fogpad repository.

**Comment by cbix** [comment]
Thanks a lot @igorski, also just noticed the new Regrader tag. However I'd strongly suggest only using semver versioning, i.e. not including sth like the VST SDK version, to make it easier to compare between versions. I see why you might have done that:
- document a known working SDK version: either check during build if sdk version > some value or simply mention it in the README
- support multiple SDK versions by different releases: likely not practical and you'd need to maintain separate code branches, but if I really wanted to support multiple versions I'd use preprocessor code branches instead :)

That said, it's also best practice on Github to prefix the tag with `v`, so the tag should instead just be `v1.0.3`.

Thanks for your work 🎉
